/**
 * A dated record, in timeline form.
 *
 * The research was consistently against a dated feed, because an abandoned one
 * signals you have stopped. That risk is real and it is managed two ways here:
 * entries are a single line each and are generated by things that already
 * happen (a paper lands, a talk is given, a campaign runs), so nothing has to
 * be written for its own sake; and the list is seeded from the CV so it is
 * never thin.
 *
 * Every entry below is a fact from the CV. Nothing is invented.
 */

export type NewsKind = "appointment" | "paper" | "award" | "talk" | "field" | "programme";

export interface NewsItem {
  /** ISO date. Month precision is fine; day is used only where it is known. */
  date: string;
  kind: NewsKind;
  title: string;
  detail?: string;
  /** Internal or external link, when there is somewhere real to go. */
  href?: string;
}

export const kindLabel: Record<NewsKind, string> = {
  appointment: "Appointment",
  paper: "Paper",
  award: "Award",
  talk: "Talk",
  field: "Field campaign",
  programme: "Programme",
};

export const news: NewsItem[] = [
  {
    date: "2026-08",
    kind: "appointment",
    title: "Started as a postdoctoral researcher at Istituto Italiano di Tecnologia (IIT), Genova",
    detail:
      "Joined the Dynamic Legged Systems lab with Claudio Semini, working on learning-based locomotion for quadrupedal robots under the ALTEC project.",
    href: "/research/legged-locomotion-for-space/",
  },
  {
    date: "2026-03",
    kind: "appointment",
    title: "Completed doctoral research at the Space Robotics Lab, Tohoku University",
    detail: "Three years on modular reconfigurable lunar robots under JST Moonshot Goal 3, as a Japanese Government MEXT scholar.",
  },
  {
    date: "2025-12",
    kind: "award",
    title: "Best Research Paper Award at IEEE iSpaRo 2025, Sendai",
    detail:
      "For multi-modal decentralized reinforcement learning on modular reconfigurable lunar robots.",
    href: "/publications/multi-modal-decentralized-rl-modular-lunar-robots/",
  },
  {
    date: "2025-10",
    kind: "field",
    title: "Mapped Abukuma Cave with the modular plug-and-play sensor box",
    detail:
      "A lunar cave analogue, fusing a Livox Mid-360 LiDAR, two fisheye cameras and an Intel RealSense D435i.",
    href: "/projects/plug-and-play-modular-sensor-box/",
  },
  {
    date: "2025-10",
    kind: "paper",
    title: "MoonBot published in IEEE Transactions on Field Robotics",
    detail: "The full modular platform for lunar base construction, with equal authorship.",
    href: "/publications/moonbot-modular-reconfigurable-robot-moon-base/",
  },
  {
    date: "2025-10",
    kind: "talk",
    title: "Invited panelist at the IAF Next Generation Plenary, IAC 2025, Sydney",
  },
  {
    date: "2025-10",
    kind: "award",
    title: "Recognised as an IAF Emerging Space Leader",
    detail: "Awarded by the International Astronautical Federation, with a grant for IAC 2025.",
  },
  {
    date: "2025-10",
    kind: "paper",
    title: "Motion Stack limb synchronization presented at IEEE/RSJ IROS 2025",
    href: "/publications/multi-limb-synchronization-motion-stack-hypersphere/",
  },
  {
    date: "2025-08",
    kind: "paper",
    title: "Human-in-the-loop manipulator control presented at IEEE CASE 2025",
    href: "/publications/human-in-loop-manipulator-control-uncertain-assembly/",
  },
  {
    date: "2025-07",
    kind: "field",
    title: "Field-validated MoonBot APEX at the JAXA Space Exploration Test Field, Sagamihara",
    detail:
      "Full-scale test of agentic planning and execution for modular lunar robots in lunar-analogue terrain and lighting.",
    href: "/projects/moonbot-apex-agentic-planning-execution/",
  },
  {
    date: "2025-03",
    kind: "field",
    title: "Tested reinforcement learning policies on morphology-varying robots at JAXA Sagamihara",
    href: "/projects/modular-rl-policy-reconfigurable-robots/",
  },
  {
    date: "2024-11",
    kind: "field",
    title: "Manipulator deployment campaign for solar infrastructure at JAXA Sagamihara",
    href: "/projects/manipulator-control-solar-infrastructure-deployment/",
  },
  {
    date: "2024-08",
    kind: "programme",
    title:
      "Led project management for the International Lunar University at the ISU Space Studies Program",
    detail:
      "Hosted at NASA Johnson Space Center and Rice University, under Dr. Jacob Cohen, Chief Scientist at NASA Ames.",
    href: "/projects/international-lunar-university-ssp24/",
  },
  {
    date: "2024-06",
    kind: "award",
    title: "Received the I-CON Award from the Indian Society of Remote Sensing and ISRO",
    detail:
      "For an AI-enabled satellite-based air pollution monitoring and alert system, developed with NRSC-ISRO scientists.",
  },
  {
    date: "2024-05",
    kind: "award",
    title: "Awarded a Tohoku University Dispatch Program Grant of EUR 20,000",
    detail: "To attend the International Space University Space Studies Program 2024.",
  },
  {
    date: "2023-10",
    kind: "appointment",
    title: "Began doctoral research at the Space Robotics Lab, Tohoku University",
    detail: "As a Japanese Government MEXT Research Scholar, with Prof. Kazuya Yoshida.",
  },
];

/** Newest first, grouped by year for the timeline. */
export const newsByYear = () => {
  const groups = new Map<string, NewsItem[]>();
  for (const n of [...news].sort((a, b) => b.date.localeCompare(a.date))) {
    const y = n.date.slice(0, 4);
    if (!groups.has(y)) groups.set(y, []);
    groups.get(y)!.push(n);
  }
  return [...groups.entries()];
};

export const latestNews = (n = 4) =>
  [...news].sort((a, b) => b.date.localeCompare(a.date)).slice(0, n);
